name:                learning-rwh
version:             0.1.0.0
github:              "githubuser/learning-rwh"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/learning-rwh#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- bytestring
- regex-posix
- filepath
- time
- QuickCheck
- array
- containers
- random
- mtl

library:
  source-dirs: src
  exposed-modules:
    - Lib
    - Ch10.Parse
    - Ch10.PNM
    - Ch12.Barcode
    - Ch13.DList
    - Ch14.Logger
    - Ch14.Carrier
  other-modules: []

executables:
  learning-rwh-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learning-rwh

tests:
  learning-rwh-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learning-rwh
